export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";


export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const CREATE_MOVIES_REQUEST = "CREATE_MOVIES_REQUEST";
export const CREATE_MOVIES_SUCCESS = "CREATE_MOVIES_SUCCESS";
export const CREATE_MOVIES_FAILURE = "CREATE_MOVIES_FAILURE";

export const DELETE_MOVIES_REQUEST = "DELETE_MOVIES_REQUEST";
export const DELETE_MOVIES_SUCCESS = "DELETE_MOVIES_SUCCESS";
export const DELETE_MOVIES_FAILURE = "DELETE_MOVIES_FAILURE";


export const UPDATE_MOVIES_REQUEST = "UPDATE_MOVIES_REQUEST";
export const UPDATE_MOVIES_SUCCESS = "UPDATE_MOVIES_SUCCESS";
export const UPDATE_MOVIES_FAILURE = "UPDATE_MOVIES_FAILURE";

export const FETCH_ONE_MOVIE_REQUEST = "FETCH_ONE_MOVIE_REQUEST ";
export const FETCH_ONE_MOVIE_SUCCESS = "FETCH_ONE_MOVIE_SUCCESS";
export const FETCH_ONE_MOVIE_FAILURE = "FETCH_ONE_MOVIE_FAILURE";

export const FILTER_MOVIE_REQUEST = "FILTER_MOVIE_REQUEST ";
export const FILTER_MOVIE_SUCCESS = "FILTER_MOVIE_SUCCESS";
export const FILTER_MOVIE_FAILURE = "FILTER_MOVIE_FAILURE";

export const EDIT_ON = "EDIT_ON";